version: '3'
services: 
    redis:
        image: redis:latest
        ports: 
            - 6379:6379
        volumes: 
            - ./config/redis.conf:/redis.conf
        command: ["redis-server", "/redis.conf"]
    posgresdb:
        image: postgres:latest
        env_file:
            - ./config/postgresdb.env
        volumes: 
            - database-data:/var/lib/postgresql/data/


volumes:
    database-data:
